propel:
  _attributes:        { package: plugins.sfPropelAuditPlugin.lib.model }

  sf_audit:
    _attributes:      { phpName: sfAudit, package: plugins.sfPropelAuditPlugin.lib.model }
    id:                 { phpName: ID, type: integer, required: true, primaryKey: true, autoincrement: true }
    remote_ip_address:  varchar(255)
    object:             varchar(255)
    object_key:         varchar(255)
    object_changes:     longvarchar
    query:              longvarchar
    user:               varchar(255)
    type:               varchar(255)
    created_at: